name: clasp

env:
  CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
  DEPLOYMENT: ${{ secrets.DEV_DEPLOYMENT }}
  SCRIPT_ID: ${{ secrets.DEV_SCRIPT_ID }}

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: deploy-clasp
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: setup node.js
      uses: actions/setup-node@v1

    - name: install clasp
      run: npm i @google/clasp -g

    - name: setup clasprc
      run: |
        echo ${CLASPRC_JSON} > ~/.clasprc.json

    - name: sed script id
      run: |
        sed -i -e "s/1q6ZgFFw6IuFWV9bHVJKsxGR1snJTXK01-AzwBOuOot-SknB2cLB4SYBU/$SCRIPT_ID/" ./.clasp.json

    - name: push
      run: clasp push --force

    - name: deploy
      run: clasp deploy -i ${DEPLOYMENT}
